version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flask-app:
    build: .
    container_name: flask-app
    restart: always
    ports:
      - "80:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SHORT_CACHE_TTL=300
      - FALLBACK_CACHE_TTL=2592000
      - CSV_FALLBACK_DIR=data/fallback
      - APP_HOST=0.0.0.0
      - APP_PORT=5000

volumes:
  redis_data:
    driver: local 